// USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_USER = 'CLEAR_USER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FETCH_EXAM = 'FETCH_EXAM';
export const CLEAR_CURRENT_EXAM = 'CLEAR_CURRENT_EXAM';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_PUBLIC_USER = 'FETCH_PUBLIC_USER';

//App

export const ADD_USER_TO_APP = 'ADD_USER_TO_APP';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';


export const WITH_FIREBASE = 'WITH_FIREBASE';
export const NOT_WITH_FIREBASE = 'NOT_WITH_FIREBASE';


//messenger 
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const UPDATE_MESSENGER = 'UPDATE_MESSENGER';
export const FETCH_MORE_MESSAGES = 'FETCH_MORE_MESSAGES';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const INIT_MESSAGES = 'INIT_MESSAGES';
export const UPDATE_CURRENT_ROOM = 'UPDATE_CURRENT_ROOM';
export const FETCH_MORE_ROOMS = 'FETCH_MORE_ROOMS';
export const UPDATE_NEW_ROOM = 'UPDATE_NEW_ROOM';
export const FETCH_MORE_NOTIFICATIONS = 'FETCH_MORE_NOTIFICATIONS';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const PUSH_NEW_NOTIFICATION = 'PUSH_NEW_NOTIFICATION';
export const DELETE_ROOM = 'DELETE_ROOM';
export const HAS_UNCHECKED_MSG = 'HAS_UNCHECKED_MSG';
export const CHECKED_ALL_MSGS = 'CHECKED_ALL_MSGS';

export const UPDATE_FRIENDS = 'UPDATE_FRIENDS';
export const UNFRIEND = 'UNFRIEND';
export const ADD_FRIEND = 'ADD_FRIEND';

export const OFF_SNACK = 'OFF_SNACK';
export const ON_SNACK = 'OFF_SNACK'
